server:
  port: 9000

spring:

  profiles:
    active: "prod"

  application:
    name: "cards"

  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root

  jpa:
    show-sql: true

  # Ejecuta los queries que estén en resources/schema.sql siempre y cuando no sea H2, con H2 es automático
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

# Exponer endpoints de actuator, se expone un endpoint que permite la actualización de properties en runtime
# http://localhost:9000/actuator/refresh - POST
management:
  endpoints:
    web:
      exposure:
        include: "*"